### ISSUE TITLE
Can't import pyktok because missing LibreWolf profile directory?

### ISSUE THREAD

**Issue by katbrooks615** [dfreelon/pyktok#23]
Hi, 

I'm using Python through Jupyter Notebooks on Firefox's browser. I've successfully installed pyktok, but it isn't letting me `import pyktok as pyk`. It's returning FileNotFoundError: Could not find LibreWolf profile directory. Do I need to install LibreWolf to use pyktok?

Thanks!

**Comment by dfreelon** [comment]
I hadn't heard of LibreWolf before you posted this issue, so I'm pretty sure it's not a pyktok dependency. Maybe try a different browser or Python shell?

**Comment by pkreissel** [comment]
It is part of browser_cookie3==0.19
If you downgrade to browser_cookie3==0.18 the error disappears. However it seems browser cookie itself is super unreliable, so I would suggest to use another dependency entirely.

**Comment by krisfur** [comment]
The issue is indeed with browser_cookie3, namely the `cookies = browser_cookie3.load()` call in pyktok.py at line [40](https://github.com/dfreelon/pyktok/blob/f9ec92ea699121426fca2ba768dfac65c45b18df/src/pyktok/pyktok.py#L40C1-L40C33) -> if you change it to a specific browser instead like `cookies = browser_cookie3.chrome(domain_name='www.tiktok.com')` it works again.

**Comment by dfreelon** [comment]
This has been fixed.
