### ISSUE TITLE
save_tiktok_multi_page returns None

### ISSUE THREAD

**Issue by yueqingliang1** [dfreelon/pyktok#8]
Hi @dfreelon, thank you very much for solving the issue of TikTokApi recently. I have checked your comments and tried to use the save_tiktok_multi_page function to retrieve videos with hashtags as follows. 
"videos = pyk.save_tiktok_multi_page('https://www.tiktok.com/tag/genderdysphoria?lang=en', save_video=False,save_metadata=True)", the hashtag is "genderdysphoria".

However, this returns None. But as you mentioned, save_tiktok_multi_page should return up to 15 videos. How can I use it to do that?

**Comment by dfreelon** [comment]
OK so this is expected behavior--if you look at the function, it lacks a `return` statement, which makes it return `None`. All `pyktok`'s "save" functions return `None`, while its "get" functions return data. I made this choice to ensure that data could be captured continuously in case of a network interruption or other error, which might otherwise cause all data collected up to that point to be lost.

If you look in your working directory after running `save_tiktok_multi_page`, you should see a CSV file containing your data. But I should add a print statement at the end indicating that the data has been saved--the other functions have that but I guess I forgot to add one to `save_tiktok_multi_page`. I'll include it in the next update.

**Comment by dfreelon** [comment]
Closing per the above.
